name: Update price list from Google Sheets

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 6 * * *"  # daily 06:15 UTC (~07:15 UK during winter; ~07:15-08:15 with DST)

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build price list
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
          TARGET_HTML: index.html             # change if your page lives elsewhere
          JSON_OUT: site/data/prices.json     # optional
          WRITE_JSONLD: "0"                   # set to "1" after mapping columns in the script
          CURRENCY: "GBP"
        run: |
          python scripts/build_prices.py

      # Create a PR only if there are changes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update price list from Google Sheets"
          title: "Update price list from Google Sheets"
          body: "Automated update."
          branch: "prices/update"
          delete-branch: true
